testengine/testengine/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('testing/', include('testing.urls')),
]

testengine/testing/urls.py
from django.urls import path

from . import views

app_name = 'testing'

urlpatterns = [
    path('list/', views.index, name='tests_index'),
    path('list/<str:slug>/', views.TestDetail.as_view(), name='test_detail_url'),
    path('questions/', views.QuestionsView.as_view(), name='questions_url'),
    path('questions/create/', views.QuestionCreate.as_view(), name='question_create_url'),
    path('questions/update/<int:id>/', views.QuestionUpdate.as_view(), name='question_update_url'),
    path('questions/delete/<int:id>/', views.QuestionDelete.as_view(), name='question_delete_url'),

]

testengine/testing/models.py
from django.db import models
from django.shortcuts import reverse
from django.template.defaultfilters import slugify

# Create your models here.

class Question(models.Model):
    question = models.TextField(db_index=True)

    def __str__(self):
        return self.question

class Answer(models.Model):
    answer = models.TextField(blank=True, null=True)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)


class Test(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    description = models.TextField(db_index=True)
    slug = models.SlugField(max_length=150, unique=True, blank = True)
    questions = models.ManyToManyField('Question', related_name='tests')


    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.title)

        super(Test, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('testing:test_detail_url', kwargs={'slug': self.slug})
    
    def __str__(self):
        return self.title


class TestRun(models.Model):
    test = models.ForeignKey('Test', on_delete=models.CASCADE)
    started = models.DateTimeField(auto_now_add=True)
    finished = models.DateTimeField(auto_now=True)

testengine/testing/forms.py
from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question',]

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'})
        }

testengine/testengine/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'index.html')

testengine/testing/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView
from django.db.models import Q
from django.views.generic import ListView

from .models import Test, Question
from .forms import QuestionForm

# Create your views here.
def index(request):
    search_query = request.GET.get('search', '')
    
    if search_query:
        tests = Test.objects.filter(Q(title__icontains=search_query) | Q(description__icontains=search_query))
    else:
        tests = Test.objects.all()
    

    return render(request, 'testing/index.html', context={'tests': tests})

# def questions(request):
#     questions_list = Question.objects.all()
#     return render(request, 'testing/questions.html', context={'questions': questions_list})

# def test_detail(request, slug):
#     test = Test.objects.get(slug__iexact=slug)
#     return render(request, 'testing/test_detail.html', context={'test': test})

class TestDetail(ListView):
    def get(self, request, slug):
        test = get_object_or_404(Test, slug__iexact=slug)
        return render(request, 'testing/test_detail.html', context={'test': test})

class QuestionsView(ListView):
    def get(self, request):
        questions = Question.objects.all()
        return render(request, 'testing/questions.html', context={'questions': questions})


class QuestionCreate(ListView):
    def get(self, request):
        form = QuestionForm()
        return render(request, 'testing/question_create.html', context={'form': form})

    def post(self, request):
        bound_form = QuestionForm(request.POST)
        if bound_form.is_valid:
            new_question = bound_form.save()
            return redirect(reverse('testing:questions_url'))
        return render(request, 'testing/question_create.html', context={'form': bound_form})

class QuestionUpdate(ListView):
    def get(self, request, id):
        question = Question.objects.get(id__exact = id)
        bound_form = QuestionForm(instance=question)
        return render(request, 'testing/question_update.html', context={'form': bound_form, 'question': question,})

    def post(self, request, id):
        question = Question.objects.get(id__exact = id)
        bound_form = QuestionForm(request.POST, instance=question)

        if bound_form.is_valid():
            updated_question = bound_form.save()
            return redirect(reverse('testing:questions_url'))
        return render(request, 'testing/question_update.html', context={'form': bound_form, 'question': question})


class QuestionDelete(ListView):
    def get(self, request, id):
        question = Question.objects.get(id__exact = id)
        return render(request, 'testing/question_delete.html', context={'question': question})

    def post(self, request, id):
        question = Question.objects.get(id__exact = id)
        question.delete()
        return redirect(reverse('testing:questions_url'))

testengine/templates/base.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'testing/css/testing.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}

        {% endblock %} | Django app
    </title>
</head>
<body>
    <nav class="navbar navbar-inverse" id = "mynavbar">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">Testing</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a class="nav_text" href="{% url 'testing:tests_index' %}">Tests</a></li>
                    <li><a class="nav_text" href="{% url 'testing:questions_url' %}">Questions</a></li>
                    <li><a href=""><span class="nav_text">Add test</span></a></li>
                </ul>
                <form class="navbar-form navbar-left" action="{% url 'testing:tests_index' %}">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Enter your request" name="search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div class="container mt-5">
        <div class="row">
                <div ng-view class="col-xs-1"></div>
                <div ng-view class="col-xs-6 content">
                    <h1>
                        {% block content_title %}
                
                        {% endblock %}
                    </h1>
                
                        {% block content %}
                
                        {% endblock %}
                </div>
                <div ng-view class="col-xs-5"></div>
        </div>     
    </div>
           

</body>


</html>

testengine/templates/index.html
{% extends 'base.html' %}

{% block title %}
    The best site for testing
{% endblock %}

{% block content_title %}
    <h1>Best site for testing.</h1>
    <h2>This site is going to help you making awesome tests.</h2>
{% endblock %}

{% block content %}

 {% endblock %}

testengine/testing/templates/testing/base_testing.html
{% extends 'base.html' %}

testengine/testing/templates/testing/index.html
{% extends 'testing/base_testing.html' %}

{% block title %}
    Tests
{% endblock %}

{% block content_title %}
    List of all tests.
{% endblock %}

{% block content %}

    {% for test in tests %}
    <div class="row">
        <div class="my-custom-container">
            <div class="card w-25" style="background-color: #eee;">
                    <div class="card-body">
                        <h3 class="card-title">{{ test.title}}</h5>
                        <p class="card-text">{{test.description}}</p>
                        <a href="{{ test.get_absolute_url}}" class="btn btn-primary">To the test</a>
                    </div>
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock %}

testengine/testing/templates/testing/question_create.html
{% extends 'testing/base_testing.html' %}
{% load static %}

{% block title %}
    Question create
{% endblock %}

{% block content_title %}
    Create new question
{% endblock %}

{% block content %}
    <form action="{% url 'testing:question_create_url' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}

                {{ field.label }}
                {{ field }}
            </div>
            
        {% endfor %}
        
        <button type="submit" class="btn btn-primary">Create</button>
        
    </form>
{% endblock %}

testengine/testing/templates/testing/question_delete.html
{% extends 'testing/base_testing.html' %}
{% load static %}

{% block title %}
    Delete question.
{% endblock %}

{% block content_title %}
    Delete question "{{question.question}}""
{% endblock %}

{% block content %}
    <form action="{% url 'testing:question_delete_url' question.id %}" method="POST">
        {% csrf_token %}
        <h3>Do you realy want to delete this question?</h3>
        <a href="{% url 'testing:questions_url' %}">Cancel</a>
        <button type="submit" class="btn btn-danger">Delete</button>

    </form>
{% endblock %}

testengine/testing/templates/testing/question_update.html
{% extends 'testing/base_testing.html' %}
{% load static %}

{% block title %}
    Edit question.
{% endblock %}

{% block content_title %}
    Edit question "{{question.question}}""
{% endblock %}

{% block content %}
    <form action="{% url 'testing:question_update_url' question.id%}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}

                {{ field.label }}
                {{ field }}
            </div>
            
        {% endfor %}
        
        <button type="submit" class="btn btn-primary">Update question</button>
        
    </form>
{% endblock %}

testengine/testing/templates/testing/questions.html
{% extends 'testing/base_testing.html' %}
{% load static %}

{% block title %}
    Questions
{% endblock %}

{% block content_title %}
    List of all questions.
{% endblock %}

{% block content %}

    {% for question in questions %}
    <div class="row">
        <div class="my-custom-container">
            <div class="card w-25" style="background-color: #eee;">
                    <div class="card-body">
                        <p class="card-text">{{question.question}}</p>
                        <div class="container">
                            <div class="row no-gutter">
                                <div class="col-sm-1">
                                  <a href="{% url 'testing:question_update_url' question.id %}" class="btn btn-warning" role="button">Edit</a>
                                </div>
                                <div class="col-sm-1">
                                  <a href="{% url 'testing:question_delete_url' question.id %}"class="btn btn-danger" role="button">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    {% endfor %}
     
        <a href="{% url 'testing:question_create_url' %}">
                <div class="fab"> + </div>
        </a>
    

{% endblock %}

testengine/testing/templates/testing/test_detail.html
{% extends 'testing/base_testing.html' %}

{% block title %}
    {{ test.title }}
{% endblock %}

{% block content_title %}
    <h2>{{ test.title }}</h2>
{% endblock %}

{% block content %}

    <h3>{{test.description}} </h3>
    {% for question in test.questions.all %}
        <p>{{ question }}</p>
        {% empty %}
        empty list!
  {% endfor %}
  <div class="container">
      <div class="row no-gutter">
          <div class="col-sm-1">
             <a href="#" class="btn btn-primary" role="button">Run</a>
          </div>
          <div class="col-sm-1">
            <a href="#" class="btn btn-warning" role="button">Edit</a>
          </div>
          <div class="col-sm-1">
            <a href="#" class="btn btn-danger" role="button">Delete</a>
          </div>
      </div>
  </div>


{% endblock %}